### ISSUE TITLE
Setup travis build to run tests on the Android emulator

### ISSUE THREAD

**Issue by rhardih** [rhardih/bad#3]
Initially https://github.com/benlau/qtci looks like the way to go.

### Todo

- [ ] Create travis config which installs, as minimum, Qt 5.12. See https://github.com/benlau/qtci/blob/master/.travis.yml for reference.
- [ ] Modify travis config to build [tests project](https://github.com/rhardih/bad/tree/master/tests) with installed version of Qt.
- [ ] Add install of Android emulator to travis config. [This blog post](https://medium.com/@nocnoc/android-emulators-in-thcloud-f39e11c15bfa) might be of inspiration.
- [ ] Deploy and run built version of tests project on installed emulator and extract exit code to build status.
